### ISSUE TITLE
S3_STAGING_PREFIX

### ISSUE THREAD

**Issue by kennethreitz** [heroku-python/bob-builder#16]
`$ bob build` -> remins as today
`$ bob stage` -> builds formula, deploys to staging directory.
`$ bob deploy` -> copies formula from staging to production dir

---

Also, make `bob deploy` check if a file exists first.

**Comment by dzuelke** [comment]
Make `bob stage` check if exists, too :p

**Comment by dzuelke** [comment]
Not sure about the wording, @kennethreitz. Maybe `build` and `deploy` should remain the same, and `release` or something should copy to an `S3_PRODUCTION_PREFIX`.

**Comment by dzuelke** [comment]
I think this should be closed, and users should implement their own syncing. With `UPSTREAM_S3_BUCKET` and `UPSTREAM_S3_PREFIX` there exists a convenient way of referencing dependencies in other buckets/prefixes, so that solves that aspect of this already.
