### ISSUE TITLE
wipe out build directory before build

### ISSUE THREAD

**Issue by kennethreitz** [heroku-python/bob-builder#19]

**Comment by dzuelke** [comment]
no, wipe out _before_ the build!

**Comment by kennethreitz** [comment]
ah, much better. :)

**Comment by dzuelke** [comment]
(that's better since you often want to "bob build something" and then inspect stuff)

**Comment by dzuelke** [comment]
yup and no need for a `--preserve` flag then!

**Comment by kennethreitz** [comment]
:sparkles: :cake: :sparkles:

**Comment by dzuelke** [comment]
funny, I was both needing that yesterday and thinking about hacking it in quickly :) especially useful in local Docker runs, since it's often easy to forget to clear the dir between "bob deploy" runs

**Comment by kennethreitz** [comment]
Yeah, I ran into it today. You're certainly welcome to take a stab at it — but, my backlog is pretty low right now, so I'm looking for things to fill it :)

**Comment by dzuelke** [comment]
de2a44e ? :)

**Comment by dzuelke** [comment]
Can be closed then :)
