### ISSUE TITLE
release bob-builder to pypi

### ISSUE THREAD

**Issue by stesie** [heroku-python/bob-builder#23]
Upstream buckets (as described in https://github.com/heroku/heroku-buildpack-php/blob/master/support/build/README.md) currently don't work as described, as bob-builder is actually fixed (by pull request #22) ... yet it hasn't been re-released since then and hence usage is still cumbersome

Therefore please publish a new version, even so it's just a small fix.

Thanks

**Comment by dzuelke** [comment]
Fixed: https://pypi.python.org/pypi/bob-builder/0.0.11
