### ISSUE TITLE
Support using bob-builder with no S3 credentials

### ISSUE THREAD

**Issue by edmorley** [heroku-python/bob-builder#26]
Currently it's not possible to test building using bob-builder unless you have S3 credentials, since the `boto.connect_s3()` call requires that `AWS_SECRET_ACCESS_KEY` be set (or credentials be configured via config file):
https://github.com/kennethreitz/bob-builder/blob/506a972125ce2dc52f761cac242b4057abb29184/bob/models.py#L33

Perhaps instead:
* If `S3_BUCKET` is not set, then don't attempt to connect to it, but instead use only `UPSTREAM_S3_BUCKET` (which already supports `anon=True`), to allow the build command to work.
* If the user tries to use the deploy command, then still error out if `S3_BUCKET` is not set.

This would help with debugging heroku/heroku-buildpack-python#379 :-)

**Comment by dzuelke** [comment]
Sounds good, where is the PR? ;)

**Comment by edmorley** [comment]
On the way :-)

**Comment by edmorley** [comment]
Another scenario that doesn't work is AWS credentials being set but for an unrelated AWS account. Whilst the upstream `.get_bucket()` has the `anon=True` fall-back, this doesn't occur for the main bucket, and specifying a main bucket is mandatory at the moment.

**Comment by kennethreitz** [comment]
Solved by #28
