### ISSUE TITLE
`bob --help` causes connection attempt to S3 and resultant errors

### ISSUE THREAD

**Issue by edmorley** [heroku-python/bob-builder#27]
Even when not invoking a build (eg using `bob --help`), models.py is imported by cli.py, which raises with `boto.exception.NoAuthHandlerFound` before it's had the chance to print the help message saying which credentials to set.

Whilst #26 will prevent the exception, I'm planning on making it output a "No AWS credentials set - connecting without authentication." message, which looks strange immediately prior to the usage help text when using `bob --help`.

Two options:
1) Move the `from .models import Formula` in cli.py into `build()`
2) Move the connection initialisation in models.py into the `Formula()` constructor (and possibly as a utils.py helper)

Thoughts?

**Comment by kennethreitz** [comment]
Solved by #28
